site_name: "nf-modules-template"
site_description: "Copier template for an nf-core modules repository"
site_url: "https://nf-core.github.io/modules-template"
repo_url: "https://github.com/nf-core/modules-template"
repo_name: "nf-core/modules-template"

validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn

nav:
  - Home:
      - Overview: index.md
      - License: license.md

theme:
  name: material
  icon:
    logo: material/currency-sign
  features:
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - search.highlight
    - search.suggest
    - toc.follow
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: purple
      accent: blue-grey
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blurple
      accent: blue-grey
      toggle:
        icon: material/weather-night
        name: Switch to system preference

markdown_extensions:
  - admonition
  - callouts
  - pymdownx.emoji
  - pymdownx.magiclink
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist
  - toc:
      permalink: "¤"

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/nf-core/modules-template
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/nf_core
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/nf-core/posts/
